services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: Vocare_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./VocareWebAPI         
      dockerfile: Dockerfile          
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: |
        Host=db;Port=5432;Database=Vocare_db;Username=postgres;Password=postgrespw;
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend            
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://api:8080
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db-data:
