version: "3.9"
services:
  api:
    build:
      context: ./VocareWebAPI
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - PerplexityAI__ApiKey=${PerplexityAI__ApiKey}
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Vocare_db;Username=postgres;Password=postgrespw;
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
    environment:
      - NODE_ENV=production
      - PerplexityAI__ApiKey=${PerplexityAI__ApiKey}
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:

volumes:
  db-data:
