version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=Vocare_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

  api:
    build:
      context: ./VocareWebAPI
      dockerfile: Dockerfile
    environment:
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Vocare_db;Username=postgres;Password=postgrespw;
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
    environment:
      - NODE_ENV=production
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:

volumes:
  db-data: