export enum PersonalityType {
  Mediator = 1,
  Advocate,
  Logician,
  Architect,
  Campaigner,
  Protagonist,
  Debater,
  Commander,
  Adventurer,
  Defender,
  Virtuoso,
  Logistician,
  Entertainer,
  Consul,
  Entrepreneur,
  Executive,
  Unknown,
}

export const personalityTypeLabels: Record<string, string> = {
  0: 'Unknown',
  1: 'Mediator',
  2: 'Advocate',
  3: 'Logician',
  4: 'Architect',
  5: 'Campaigner',
  6: 'Protagonist',
  7: 'Debater',
  8: 'Commander',
  9: 'Adventurer',
  10: 'Defender',
  11: 'Virtuoso',
  12: 'Logistician',
  13: 'Entertainer',
  14: 'Consul',
  15: 'Entrepreneur',
  16: 'Executive',
  17: 'Unknown',
};
